name: github action demo pipeline

on:
  push:
    branches:
      - main

jobs:
  extract-job:
    name: Extract Data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run extract.py
        run: python .github/workflows/extract.py

  transform-job:
    name: Transform Data
    runs-on: ubuntu-latest
    needs: extract-job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run transform.py
        run: python .github/workflows/transform.py

  load-job:
    name: Load Data
    runs-on: ubuntu-latest
    needs: transform-job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run load.py
        run: python .github/workflows/load.py
